### PR TITLE
Sharp dock icon

### PR DESCRIPTION
**Pull request by luisrguerra**
Improved icon resolution. Remade icon aligned to 12x12 pixel grade for better resolution when the icon is resized to 12x12 at ui. Similar to [Pull Request #7](https://github.com/gnu-octave/octave/pull/7) .
paintdotnet_Vxbv3z8J4u
paintdotnet_0UQEpJIbhG

### CODE REVIEW

**Comment by mmuetzel** [comment]
It looks like these changes have been pushed to the upstream Mercurial repository here:
https://hg.savannah.gnu.org/hgweb/octave/rev/dfd2f1db0291

That synchronized to this commit on GitHub:
https://github.com/gnu-octave/octave/commit/ab1eee1a485a19c40aa13cc394fce4632ea9c784

Thank you for your contribution.

Closing PR.

**Comment by ttlmax** [comment]
@luisrguerra, thank you very much for the patch.

The changeset  https://hg.savannah.gnu.org/hgweb/octave/rev/dfd2f1db0291 merged a previous patch (merge request #7) into the official repo. However, I have already updated the dock and close icon with changeset https://hg.savannah.gnu.org/hgweb/octave/rev/88c7a53b8373 following the changes that were made for the undock icon.

**Comment by luisrguerra** [comment]
> The changeset https://hg.savannah.gnu.org/hgweb/octave/rev/dfd2f1db0291 merged a previous patch (merge request #7) into the official repo. However, I have already updated the dock and close icon with changeset https://hg.savannah.gnu.org/hgweb/octave/rev/88c7a53b8373 following the changes that were made for the undock icon.

Check the files, the pull request which I uploaded fix a blur in the middle of the current icon when it's resized to 12x12

**Comment by mmuetzel** [comment]
I can confirm that this proposed image is less blurry when rescaled to 12x12 px.

**Comment by ttlmax** [comment]
Resolved conflicts and merged with http://hg.savannah.gnu.org/hgweb/octave/rev/9ad410b8480c

Thanks for the patch.

**Pull request closed without merging**
