### PR TITLE
fix typo in doc, cos(angle) = dot(x,y)/(norm(x)*norm(y))

### PR DESCRIPTION
**Pull request by hpodhaisky**
the right hand side is for the **reciprocal** angles

### CODE REVIEW

**Comment by siko1056** [comment]
Thank you for the contribution @hpodhaisky :pray: 

@mmuetzel Can you make the upstream change?

https://en.wikipedia.org/wiki/Dot_product#Geometric_definition

**Comment by mmuetzel** [comment]
@hpodhaisky: Thank you for your contribution.
This is just a read-only mirror of the upstream Mercurial repository of Octave.
I'd like to apply your proposed change there. However, this is just a read-only mirror of the upstream Mercurial repository of Octave. I'd be happy to push it with you as the author to the Mercurial repository. But I'd need your name (usually first and last name of the author) and a valid email address. Could you please let me know what I could use?

Alternatively, if you prefer to not share that information, I could push that change with my credentials.

Please, let us know what you prefer.

**Comment by hpodhaisky** [comment]
Dear Markus @mmuetzel ,

please make the upstream changes using:

"Helmut Podhaisky <helmut.podhaisky@mathematik.uni-halle.de>"

Thanks for your work. I am using octave for decades -- and it is very nice.

Helmut

**Comment by mmuetzel** [comment]
I pushed your change to the Mercurial repository:
https://hg.savannah.gnu.org/hgweb/octave/rev/a310f09b720a

**Pull request closed without merging**
