### PR TITLE
New icons

### PR DESCRIPTION
**Pull request by luisrguerra**
### [luisrguerra/cc0-fluent-icons](https://github.com/luisrguerra/cc0-fluent-icons)

chrome_8nIJCd6jVm chrome_shABbxFWWu chrome_LxVX9wGG7U chrome_HGBP6kaJTm chrome_8zuNl1JaHL chrome_ghCPFwcp0T document-save document-save-as edit-undo edit-redo

Preview:

preview1

preview2v2

Octave 6.4:
154780765-b71494fb-193e-4744-9583-e21a40618e06
153879215-6cf5c621-1e46-4fbd-ba9d-0391528b5492

### CODE REVIEW

**Comment by luisrguerra** [comment]
@ttlmax @siko1056 @mmuetzel I'm finishing the main icons that are more visible in the interface, is there any specific that you want me to do?

**Comment by ttlmax** [comment]
You are a lot faster than me :-).
I am currently still working on the possibility to select the icon theme
 togehter with a consistent separation of the tango icon theme and the new "octave" theme. Afterwards I will add your icons with new changesets as merging would be difficult due to the new folder structure.

**Comment by ttlmax** [comment]
I am currently including the new icons in  a patch that does not conflict with the new icon folder structure. Is debug-play intended to replace db-cont? If yes, why the new name?

**Comment by luisrguerra** [comment]
> I am currently including the new icons in a patch that does not conflict with the new icon folder structure. Is debug-play intended to replace db-cont? If yes, why the new name?

[The icon name was wrong, it was fixed in the last commits](https://github.com/gnu-octave/octave/pull/14/commits/1a7cb0f591c4f8f7e60d672a608afcbadcd673e2),  check the latest commits for the latest version of the icons. Once you've added the icons, close this pull request so I can stay aware and get organized to make future pull request on the correct directory.

**Comment by ttlmax** [comment]
Changeset http://hg.savannah.gnu.org/hgweb/octave/rev/16023ccebcca adds the new icons into the "octave" icon theme. I hope I have not missed an icon. If everything is okay, I will close this pull request.

**Comment by luisrguerra** [comment]
> Changeset http://hg.savannah.gnu.org/hgweb/octave/rev/16023ccebcca adds the new icons into the "octave" icon theme. I hope I have not missed an icon. If everything is okay, I will close this pull request.

After this pull request you need to implement [this other pull request with applications-system and system-run new icons](https://github.com/gnu-octave/octave/pull/11) which is separate as the icons need to be implemented in code due to the changing of the meaning of the icons, which could cause conflicts (of meaning) in other places of the interface where these icons are used.

**Comment by luisrguerra** [comment]
I believe this pull request is ready to be closed

**Comment by ttlmax** [comment]
I have just added the two icons from the other pull request. The "folder-settings" icon is not included in the [standard icon naming specification](https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html) (as far as I know. This would lead to problems using different icon themes.

**Comment by mmuetzel** [comment]
Oops. I wasn't aware of that standard and added willy-nilly a new icon `folder-up` as part of this changeset:
https://github.com/gnu-octave/octave/commit/be9d924e22221a7617d7781c24b3a59d07ca9f5b

Maybe that should also be revisited...

**Comment by ttlmax** [comment]
Don't worry, we already have non-standard icons. As suggested in the other thread, we can provide the possibility to select a non-standard icon and provide the name of the "nearest" standard icon as fallback if a theme does not have the non-standard icon.

**Pull request closed without merging**
