### PR TITLE
go-home icon

### PR DESCRIPTION
**Pull request by luisrguerra**
Need to implement in the code
go-home

Tango icon:
go-home

Preview:
preview

### CODE REVIEW

**Comment by ttlmax** [comment]
@siko1056, while closing this merge request, have you pushed the patch into the hg repository?

**Comment by ttlmax** [comment]
@luisrguerra, thanks for the new icon. When looking at your screenshot, I get the impression that the zoom icons are a little bit too bold. What do you think?

And, in order to avoid misunderstandings with adding and removing actions, what do you think of a small magnifying glass around the symbols (although the old icons hadn't this either)?

**Comment by luisrguerra** [comment]
> And, in order to avoid misunderstandings with adding and removing actions, what do you think of a small magnifying glass around the symbols (although the old icons hadn't this either)?

I thought about doing it like magnifying glass, I just didn't do it to not change the meaning of the icon. I can do it in the future

**Comment by luisrguerra** [comment]
> @luisrguerra, thanks for the new icon. When looking at your screenshot, I get the impression that the zoom icons are a little bit too bold. What do you think?

I think it became a little too bold because it was made aligned to the 8x8 pixel grid

**Comment by siko1056** [comment]
@ttlmax This report was not intentionally closed by me.  This is a side effect of deleting the accidentally created branch in this git clone of the Octave hg repository.

I did not push any changes, but cannot reopen this report either without creating the "new-icons4" branch again.

@luisrguerra Thank you very much for your contributions.  We really appreciate this :slightly_smiling_face: :+1:  When creating PRs, please make sure to use "default" or "stable" as target branch to make them easy to merge :wink:

**Comment by luisrguerra** [comment]
> @ttlmax This report was not intentionally closed by me. This is a side effect of deleting the accidentally created branch in this git clone of the Octave hg repository.
> 
> I did not push any changes, but cannot reopen this report either without creating the "new-icons4" branch again.
> 
> @luisrguerra Thank you very much for your contributions. We really appreciate this 🙂 👍 When creating PRs, please make sure to use "default" or "stable" as target branch to make them easy to merge 😉

I accidentally opened a branch in the official repository but I wasn't having permission to delete the branch I created myself. What doesn't make sense, seems to be some bug or conflict. I will redo the pull request in the future with the new changes with magnifying glass icons.

**Pull request closed without merging**
